version: '2.1'

services:

  aws-vault:
    build: .
    environment:
      - AWS_VAULT_BACKEND
      - AWS_VAULT_FILE_PASSPHRASE
    volumes:
      - ~/.aws:/root/.aws
      - ~/.awsvault:/root/.awsvault

  dev:
    image: golang
    volumes:
      - .:/aws-vault
      - /root/.aws
      - /root/.awsvault
    working_dir: /aws-vault
    entrypoint: go run main.go
